name: Deploy on AWS Elastic Beanstalk

env:
  APP_NAME: snake
  APP_ENV_NAME: Snake-env-1
  AWS_REGION: sa-east-1
  AWS_PLATFORM: Docker
  PIPELINE_ID: ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy_aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'

      - name: Create Env File
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: '.env'
          encodedString: ${{ secrets.ENV_FILE }}

      - name: Copy Env File from Temporary Path
        run: cp ${{ steps.write_file.outputs.filePath }} ./.env

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: |
          AWS_VERSION_LABEL=${{env.APP_NAME}}-${{env.PIPELINE_ID}}

          echo "Installing Elastic Beanstalk Cli"
          python -m pip install --upgrade pip
          pip install awsebcli --upgrade
          eb --version

          echo "Deploy init"
          eb init ${{env.APP_NAME}} -p ${{env.AWS_PLATFORM}} --region ${{env.AWS_REGION}}
          eb deploy ${{env.APP_ENV_NAME}} --version ${AWS_VERSION_LABEL}
          echo "Deploy finished"
